CREATE TABLE IF NOT EXISTS users (
    ID BIGSERIAL NOT NULL,
    Name VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()::TIMESTAMPTZ,
    favorite_book VARCHAR NULL DEFAULT NULL,
    CONSTRAINT users_pk PRIMARY KEY (ID)
);